workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - app:
          filters:
            branches:
              only: master
      - api:
          filters:
            branches:
              only: master
jobs:
  app:
    docker:
      - image: circleci/node:dubnium
    working_directory: ~/repo/app
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - app-cache-{{ checksum "yarn.lock" }}
            - app-cache-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: app-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Run unit tests
          command: yarn test
      - run:
          name: Deploy app to now.sh
          command: yarn deploy --token $ZEIT_TOKEN

  api:
    docker:
      - image: circleci/node:dubnium
    working_directory: ~/repo/api
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - api-cache-{{ checksum "yarn.lock" }}
            - api-cache-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: api-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Run unit tests
          command: yarn test
      - run:
          name: Deploy api
          command: yarn deploy:prod
