workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - app:
          filters:
            branches:
              only: master
      - api:
          filters:
            branches:
              only: master
      - e2e:
          requires:
            - app
            - api
          filters:
            branches:
              only: master
jobs:
  app:
    docker:
      - image: circleci/node:dubnium
    working_directory: ~/repo/app
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - app-cache-{{ checksum "yarn.lock" }}
            - app-cache-
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: app-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Run unit tests
          command: yarn test
      - run:
          name: Deploy app to now.sh
          command: yarn deploy --token $ZEIT_TOKEN

  api:
    docker:
      - image: circleci/node:dubnium
    working_directory: ~/repo/api
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - api-cache-2-{{ checksum "yarn.lock" }}
            - api-cache-2
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: api-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Run unit tests
          command: yarn test
      - run:
          name: Deploy api
          command: yarn deploy:prod

  e2e:
    docker:
      - image: cypress/base:10
    working_directory: ~/repo
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - e2e-cache-2-{{ checksum "yarn.lock" }}
            - e2e-cache-2
      - run:
          name: Setup Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
            - ~/.cache ## cache both yarn and Cypress
          key: e2e-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Run e2e tests
          command: CYPRESS_BASE_URL=https://bundlelove.now.sh yarn cy:run
